version = 5.7.0
archive_dir = /etc/letsencrypt/archive/vibing.ddnsfree.com
cert = /etc/letsencrypt/live/vibing.ddnsfree.com/cert.pem
privkey = /etc/letsencrypt/live/vibing.ddnsfree.com/privkey.pem
chain = /etc/letsencrypt/live/vibing.ddnsfree.com/chain.pem
fullchain = /etc/letsencrypt/live/vibing.ddnsfree.com/fullchain.pem
[renewalparams]
account = e8551e2bbf635746ecbab6607b03585a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
vibing.ddnsfree.com = /var/www/certbot
